<?php

namespace AppBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{  
	public function findBySS($location) 
	{
    	return $this->createQueryBuilder('a')
    				->select('a.title, a.description')
			        ->where('a.location = :location')
			        ->andWhere('a.activity_type = 1')
			        ->setParameter('location',$location)
			        ->getQuery() 
			        ->getResult();
	}
	public function findByOS($location) 
	{
    	return $this->createQueryBuilder('a')
    				->select('a.title, a.description')
			        ->where('a.location = :location')
			        ->andWhere('a.activity_type = 2')
			        ->setParameter('location',$location)
			        ->getQuery() 
			        ->getResult();
	}
	public function findByOT($location) 
	{
    	return $this->createQueryBuilder('a')
    				->select('a.title, a.description')
			        ->where('a.location = :location')
			        ->andWhere('a.activity_type = 3')
			        ->setParameter('location',$location)
			        ->getQuery() 
			        ->getResult();
	}
   	/*public function findByAct($location)
   	{
   		return $this->createQueryBuilder('a')
   					->leftJoin('a.activity_type', 'at')
   					->andWhere('a.location = :location')
   					->setParameter('location',$location)
			        ->getQuery() 
			        ->getResult();
   					
   	}*/	 
}
