<?php

namespace AppBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLatest($limit) 
	{
    	return $this->createQueryBuilder('e')
    				->orderBy('e.dateIns', 'DESC')
			        ->setMaxResults($limit)
			        ->getQuery() 
			        ->getResult();
	}
	public function findLatLng()
	{
		return $this->createQueryBuilder('p')
					  ->select('p.id, p.name, p.lat, p.lng')
					  ->getQuery()
					  ->getResult();
	}
}
