<?php

namespace AppBundle\Repository;

/**
 * TypeActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeActivityRepository extends \Doctrine\ORM\EntityRepository
{
	
}
