# Easy Admin Bundle
easy_admin:
    site_name: 'Admin panel'
    design:
        color_scheme: 'light'
        brand_color: '#0073AA'
    entities:
        User:
            class: AppBundle\Entity\User
            image_base_path: '/images/profile'
            disabled_actions: ['new']
            list:
                title: User list
                fields: 
                      - enabled
                      - username
                      - name
                      - surname
                      - roles
                      - email
                      - { property: 'imageName', label: 'Avatar',  type: 'image' }
            form:
                fields: 
                      - enabled
                      - name
                      - surname
                      - username
                      - email
                      - city
                      - country
                      - { property: 'plainPassword', type: 'password', label: 'Password' }
                      - roles 
                      - lastLogin
                      - { property: 'imageFile', label: 'Avatar',  type: 'file' }
        Location:
            class: AppBundle\Entity\Location
            image_base_path: '/images/profile'
            disabled_actions: 
            list:
                title: Location list
                fields: 
                      - { property: 'status', label: 'Enabled'}
                      - name
                      - category
                      - user
                      - { property: 'dateIns', label: 'Date post',  type: 'date' }
            form:
                fields: 
                      - { property: 'status', label: 'Enabled'}
                      - name
                      - category
                      - { property: description, type: 'textarea'}
                      - user
                      - { property: 'dateIns', label: 'Date post',  type: 'datetime' }